### PR TITLE
Expose entire configuration in Nix

### PR DESCRIPTION
**Pull request by jelemux**
Hey there!

I stumbled over this project of yours a few days ago and this was exactly what I was looking for!

I also share your vision of this becoming part of nixpkgs.
That's why I exposed the entire configuration in the NixOS module, no YAML necessary.
I think that this is a necessary step to create a package that is usable for everyone.

I put in a lot of hard work and tried to make it perfect, so I hope it's to your liking!
However, I'm still quite new to Nix, so if anything can be improved, I'm open to your criticism.

I also evaluated if it would be possible to expose paths to cluster secrets (CAs, kubeconfigs, join tokens) to Nix so that a tool like [sops-nix](https://github.com/Mic92/sops-nix) can be used to manage them. This would help to make builds even more deterministic so that nodes can immediately re-join after the controller was rebuilt.
I have some ideas, if you want to discuss it. CAs and possibly kubeconfigs might not be too hard, join tokens might be harder or even impossible. But for now, I concluded that this is well out of scope for me.

Looking forward to hear what you think!

### CODE REVIEW

**Comment by johbo** [comment]
Thanks for sending this in! 👍 It's gonna take me a bit of time to get to this and try it in my setup, with some luck this weekend.

**Comment by plaflamme** [comment]
FWIW: I've used this proposed branch in my own setup and works fine. Mirroring the configuration like this makes it trivial to configure 👍 

Perhaps my only recommendation would be to make the YAML human-friendly [here](https://github.com/johbo/k0s-nix/pull/4/files#diff-08d5c682c88112f5a04ecf8108e12cdb20fc9b3951c911c2eedb2dc36785001fR90) (it currently produces the config as JSON which is not particularly readable). I believe this is possible using [`pkgs.formats.yaml`](https://github.com/NixOS/nixpkgs/pull/133807)?

One question I had was why is the `pkg.k0s` not added automatically? I'm not very familiar with nix flake / modules. Shouldn't it be sufficient to import the module in my configuration? e.g.:

```nix
modules = [ k0s.nixosModules.default ];
```

Currently, I have to do this:

```nix
modules = [
  k0s.nixosModules.default
  { nixpkgs.overlays = [ k0s.overlays.default ]; }
]
```

Maybe this is something specific to my setup?

**Comment by jelemux** [comment]
> Perhaps my only recommendation would be to make the YAML human-friendly [here](https://github.com/johbo/k0s-nix/pull/4/files#diff-08d5c682c88112f5a04ecf8108e12cdb20fc9b3951c911c2eedb2dc36785001fR90) (it currently produces the config as JSON which is not particularly readable). I believe this is possible using [`pkgs.formats.yaml`](https://github.com/NixOS/nixpkgs/pull/133807)?

Huh, I didn't realize Nix had a YAML-implementation that isn't JSON. Thanks, I'll try it!

> One question I had was why is the `pkg.k0s` not added automatically? I'm not very familiar with nix flake / modules. Shouldn't it be sufficient to import the module in my configuration?

This is not specific to your setup. I guess it's because @johbo wanted to add this to nixpkgs and so for now, we'll have to use an overlay to simulate that? If that is not the case and there's no other reasons, then yes, I agree that getting rid of it would be better.

@johbo it seems that there is quite a bit of interest in your project and this PR, so could you maybe have a look and review it?
Then we could possibly move forward and add it to nixpkgs. Do you have any insights about the process of that?
I guess there will have to be an official maintainer for this package. Will this be you?

**Comment by jelemux** [comment]
@plaflamme I just added a commit to use pkgs.formats.yaml to make the k0s.yaml human-friendly. Could you take a look if this is what you intended? It was a bit tricky to indent the lines, maybe there's a function to do that somewhere in the library? If so, I couldn't find it.

**Comment by plaflamme** [comment]
@jelemux ah, yeah that's pretty nasty, I didn't realize it would make things so clunky. Perhaps the simplest thing to do is generate the whole file instead of having templating parts of it, something like this maybe:

```
configYaml = {
  apiVersion = "k0s.k0sproject.io/v1beta1";
  kind = "Cluster";
  metadata = {
    name = cfg.clusterName;
  };
  spec = cfg.spec;
}
```

and then use `configFile = (pkgs.formats.yaml {}).generate "k0s.yaml" configYaml;`

**Comment by jelemux** [comment]
Ah, why didn't I think of that!? Give me a minute, brb

**Comment by johbo** [comment]
Hi! I am fine to merge this without waiting for myself finding the time to try it on my configuration, I can also later do this.

Is it from your en in a ready state? @jelemux ?

Also maybe related to your comment above, I've just started a discussion if we could consider putting this repo in a share place to avoid myself slowing things down, see https://github.com/johbo/k0s-nix/issues/7 .

**Pull request merged**
